/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddressBalance {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "balance")]
    pub balance: String,
    #[serde(rename = "balanceHint")]
    pub balance_hint: String,
    #[serde(rename = "lockedBalance")]
    pub locked_balance: String,
    #[serde(rename = "lockedBalanceHint")]
    pub locked_balance_hint: String,
}

impl AddressBalance {
    pub fn new(address: String, balance: String, balance_hint: String, locked_balance: String, locked_balance_hint: String) -> AddressBalance {
        AddressBalance {
            address,
            balance,
            balance_hint,
            locked_balance,
            locked_balance_hint,
        }
    }
}

