/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetOutput {
    #[serde(rename = "hint")]
    pub hint: i32,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "attoAlphAmount")]
    pub atto_alph_amount: String,
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "tokens")]
    pub tokens: Vec<models::Token>,
    #[serde(rename = "lockTime")]
    pub lock_time: i64,
    #[serde(rename = "message")]
    pub message: String,
}

impl AssetOutput {
    pub fn new(hint: i32, key: String, atto_alph_amount: String, address: String, tokens: Vec<models::Token>, lock_time: i64, message: String) -> AssetOutput {
        AssetOutput {
            hint,
            key,
            atto_alph_amount,
            address,
            tokens,
            lock_time,
            message,
        }
    }
}

