/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Balances {
    #[serde(rename = "totalBalance")]
    pub total_balance: String,
    #[serde(rename = "totalBalanceHint")]
    pub total_balance_hint: String,
    #[serde(rename = "balances")]
    pub balances: Vec<models::AddressBalance>,
}

impl Balances {
    pub fn new(total_balance: String, total_balance_hint: String, balances: Vec<models::AddressBalance>) -> Balances {
        Balances {
            total_balance,
            total_balance_hint,
            balances,
        }
    }
}

