/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlocksPerTimeStampRange {
    #[serde(rename = "blocks")]
    pub blocks: Vec<Vec<models::BlockEntry>>,
}

impl BlocksPerTimeStampRange {
    pub fn new(blocks: Vec<Vec<models::BlockEntry>>) -> BlocksPerTimeStampRange {
        BlocksPerTimeStampRange {
            blocks,
        }
    }
}

