/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BrokerInfo {
    #[serde(rename = "cliqueId")]
    pub clique_id: String,
    #[serde(rename = "brokerId")]
    pub broker_id: i32,
    #[serde(rename = "brokerNum")]
    pub broker_num: i32,
    #[serde(rename = "address")]
    pub address: Box<models::BrokerInfoAddress>,
}

impl BrokerInfo {
    pub fn new(clique_id: String, broker_id: i32, broker_num: i32, address: models::BrokerInfoAddress) -> BrokerInfo {
        BrokerInfo {
            clique_id,
            broker_id,
            broker_num,
            address: Box::new(address),
        }
    }
}

