/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildExecuteScriptTx {
    #[serde(rename = "fromPublicKey")]
    pub from_public_key: String,
    #[serde(rename = "fromPublicKeyType", skip_serializing_if = "Option::is_none")]
    pub from_public_key_type: Option<String>,
    #[serde(rename = "bytecode")]
    pub bytecode: String,
    #[serde(rename = "attoAlphAmount", skip_serializing_if = "Option::is_none")]
    pub atto_alph_amount: Option<String>,
    #[serde(rename = "tokens", skip_serializing_if = "Option::is_none")]
    pub tokens: Option<Vec<models::Token>>,
    #[serde(rename = "gasAmount", skip_serializing_if = "Option::is_none")]
    pub gas_amount: Option<i32>,
    #[serde(rename = "gasPrice", skip_serializing_if = "Option::is_none")]
    pub gas_price: Option<String>,
    #[serde(rename = "targetBlockHash", skip_serializing_if = "Option::is_none")]
    pub target_block_hash: Option<String>,
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<i32>,
    #[serde(rename = "gasEstimationMultiplier", skip_serializing_if = "Option::is_none")]
    pub gas_estimation_multiplier: Option<f64>,
}

impl BuildExecuteScriptTx {
    pub fn new(from_public_key: String, bytecode: String) -> BuildExecuteScriptTx {
        BuildExecuteScriptTx {
            from_public_key,
            from_public_key_type: None,
            bytecode,
            atto_alph_amount: None,
            tokens: None,
            gas_amount: None,
            gas_price: None,
            target_block_hash: None,
            group: None,
            gas_estimation_multiplier: None,
        }
    }
}

