/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChainParams {
    #[serde(rename = "networkId")]
    pub network_id: i32,
    #[serde(rename = "numZerosAtLeastInHash")]
    pub num_zeros_at_least_in_hash: i32,
    #[serde(rename = "groupNumPerBroker")]
    pub group_num_per_broker: i32,
    #[serde(rename = "groups")]
    pub groups: i32,
}

impl ChainParams {
    pub fn new(network_id: i32, num_zeros_at_least_in_hash: i32, group_num_per_broker: i32, groups: i32) -> ChainParams {
        ChainParams {
            network_id,
            num_zeros_at_least_in_hash,
            group_num_per_broker,
            groups,
        }
    }
}

