/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Confirmed {
    #[serde(rename = "blockHash")]
    pub block_hash: String,
    #[serde(rename = "txIndex")]
    pub tx_index: i32,
    #[serde(rename = "chainConfirmations")]
    pub chain_confirmations: i32,
    #[serde(rename = "fromGroupConfirmations")]
    pub from_group_confirmations: i32,
    #[serde(rename = "toGroupConfirmations")]
    pub to_group_confirmations: i32,
}

impl Confirmed {
    pub fn new(block_hash: String, tx_index: i32, chain_confirmations: i32, from_group_confirmations: i32, to_group_confirmations: i32) -> Confirmed {
        Confirmed {
            block_hash,
            tx_index,
            chain_confirmations,
            from_group_confirmations,
            to_group_confirmations,
        }
    }
}

