/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Constant {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "value")]
    pub value: Box<models::Val>,
}

impl Constant {
    pub fn new(name: String, value: models::Val) -> Constant {
        Constant {
            name,
            value: Box::new(value),
        }
    }
}

