/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractEventByBlockHash {
    #[serde(rename = "txId")]
    pub tx_id: String,
    #[serde(rename = "contractAddress")]
    pub contract_address: String,
    #[serde(rename = "eventIndex")]
    pub event_index: i32,
    #[serde(rename = "fields")]
    pub fields: Vec<models::Val>,
}

impl ContractEventByBlockHash {
    pub fn new(tx_id: String, contract_address: String, event_index: i32, fields: Vec<models::Val>) -> ContractEventByBlockHash {
        ContractEventByBlockHash {
            tx_id,
            contract_address,
            event_index,
            fields,
        }
    }
}

