/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DebugMessage {
    #[serde(rename = "contractAddress")]
    pub contract_address: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl DebugMessage {
    pub fn new(contract_address: String, message: String) -> DebugMessage {
        DebugMessage {
            contract_address,
            message,
        }
    }
}

