/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GhostUncleBlockEntry {
    #[serde(rename = "blockHash")]
    pub block_hash: String,
    #[serde(rename = "miner")]
    pub miner: String,
}

impl GhostUncleBlockEntry {
    pub fn new(block_hash: String, miner: String) -> GhostUncleBlockEntry {
        GhostUncleBlockEntry {
            block_hash,
            miner,
        }
    }
}

