/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Enum {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "fields")]
    pub fields: Vec<models::EnumField>,
}

impl Enum {
    pub fn new(name: String, fields: Vec<models::EnumField>) -> Enum {
        Enum {
            name,
            fields,
        }
    }
}

