/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeVersion {
    #[serde(rename = "version")]
    pub version: String,
}

impl NodeVersion {
    pub fn new(version: String) -> NodeVersion {
        NodeVersion {
            version,
        }
    }
}

