/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PeerMisbehavior {
    #[serde(rename = "peer")]
    pub peer: String,
    #[serde(rename = "status")]
    pub status: Box<models::PeerStatus>,
}

impl PeerMisbehavior {
    pub fn new(peer: String, status: models::PeerStatus) -> PeerMisbehavior {
        PeerMisbehavior {
            peer,
            status: Box::new(status),
        }
    }
}

