/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum PeerStatus {
    #[serde(rename="Banned")]
    Banned(models::Banned),
    #[serde(rename="Penalty")]
    Penalty(models::Penalty),
}

impl Default for PeerStatus {
    fn default() -> Self {
        Self::Banned(Default::default())
    }
}


