/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PeerAddress {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "restPort")]
    pub rest_port: i32,
    #[serde(rename = "wsPort")]
    pub ws_port: i32,
    #[serde(rename = "minerApiPort")]
    pub miner_api_port: i32,
}

impl PeerAddress {
    pub fn new(address: String, rest_port: i32, ws_port: i32, miner_api_port: i32) -> PeerAddress {
        PeerAddress {
            address,
            rest_port,
            ws_port,
            miner_api_port,
        }
    }
}

