/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RichBlocksAndEventsPerTimeStampRange {
    #[serde(rename = "blocksAndEvents")]
    pub blocks_and_events: Vec<Vec<models::RichBlockAndEvents>>,
}

impl RichBlocksAndEventsPerTimeStampRange {
    pub fn new(blocks_and_events: Vec<Vec<models::RichBlockAndEvents>>) -> RichBlocksAndEventsPerTimeStampRange {
        RichBlocksAndEventsPerTimeStampRange {
            blocks_and_events,
        }
    }
}

