/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SelfClique {
    #[serde(rename = "cliqueId")]
    pub clique_id: String,
    #[serde(rename = "nodes")]
    pub nodes: Vec<models::PeerAddress>,
    #[serde(rename = "selfReady")]
    pub self_ready: bool,
    #[serde(rename = "synced")]
    pub synced: bool,
}

impl SelfClique {
    pub fn new(clique_id: String, nodes: Vec<models::PeerAddress>, self_ready: bool, synced: bool) -> SelfClique {
        SelfClique {
            clique_id,
            nodes,
            self_ready,
            synced,
        }
    }
}

