/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StructSig {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "fieldNames")]
    pub field_names: Vec<String>,
    #[serde(rename = "fieldTypes")]
    pub field_types: Vec<String>,
    #[serde(rename = "isMutable")]
    pub is_mutable: Vec<bool>,
}

impl StructSig {
    pub fn new(name: String, field_names: Vec<String>, field_types: Vec<String>, is_mutable: Vec<bool>) -> StructSig {
        StructSig {
            name,
            field_names,
            field_types,
            is_mutable,
        }
    }
}

