/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitMultisig {
    #[serde(rename = "unsignedTx")]
    pub unsigned_tx: String,
    #[serde(rename = "signatures")]
    pub signatures: Vec<String>,
}

impl SubmitMultisig {
    pub fn new(unsigned_tx: String, signatures: Vec<String>) -> SubmitMultisig {
        SubmitMultisig {
            unsigned_tx,
            signatures,
        }
    }
}

