/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Sweep {
    #[serde(rename = "toAddress")]
    pub to_address: String,
    #[serde(rename = "lockTime", skip_serializing_if = "Option::is_none")]
    pub lock_time: Option<i64>,
    #[serde(rename = "gasAmount", skip_serializing_if = "Option::is_none")]
    pub gas_amount: Option<i32>,
    #[serde(rename = "gasPrice", skip_serializing_if = "Option::is_none")]
    pub gas_price: Option<String>,
    #[serde(rename = "utxosLimit", skip_serializing_if = "Option::is_none")]
    pub utxos_limit: Option<i32>,
    #[serde(rename = "targetBlockHash", skip_serializing_if = "Option::is_none")]
    pub target_block_hash: Option<String>,
}

impl Sweep {
    pub fn new(to_address: String) -> Sweep {
        Sweep {
            to_address,
            lock_time: None,
            gas_amount: None,
            gas_price: None,
            utxos_limit: None,
            target_block_hash: None,
        }
    }
}

