/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TestContract {
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<i32>,
    #[serde(rename = "blockHash", skip_serializing_if = "Option::is_none")]
    pub block_hash: Option<String>,
    #[serde(rename = "blockTimeStamp", skip_serializing_if = "Option::is_none")]
    pub block_time_stamp: Option<i64>,
    #[serde(rename = "txId", skip_serializing_if = "Option::is_none")]
    pub tx_id: Option<String>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "callerContractAddress", skip_serializing_if = "Option::is_none")]
    pub caller_contract_address: Option<String>,
    #[serde(rename = "bytecode")]
    pub bytecode: String,
    #[serde(rename = "initialImmFields", skip_serializing_if = "Option::is_none")]
    pub initial_imm_fields: Option<Vec<models::Val>>,
    #[serde(rename = "initialMutFields", skip_serializing_if = "Option::is_none")]
    pub initial_mut_fields: Option<Vec<models::Val>>,
    #[serde(rename = "initialAsset", skip_serializing_if = "Option::is_none")]
    pub initial_asset: Option<Box<models::AssetState>>,
    #[serde(rename = "methodIndex", skip_serializing_if = "Option::is_none")]
    pub method_index: Option<i32>,
    #[serde(rename = "args", skip_serializing_if = "Option::is_none")]
    pub args: Option<Vec<models::Val>>,
    #[serde(rename = "existingContracts", skip_serializing_if = "Option::is_none")]
    pub existing_contracts: Option<Vec<models::ContractState>>,
    #[serde(rename = "inputAssets", skip_serializing_if = "Option::is_none")]
    pub input_assets: Option<Vec<models::TestInputAsset>>,
    #[serde(rename = "dustAmount", skip_serializing_if = "Option::is_none")]
    pub dust_amount: Option<String>,
}

impl TestContract {
    pub fn new(bytecode: String) -> TestContract {
        TestContract {
            group: None,
            block_hash: None,
            block_time_stamp: None,
            tx_id: None,
            address: None,
            caller_contract_address: None,
            bytecode,
            initial_imm_fields: None,
            initial_mut_fields: None,
            initial_asset: None,
            method_index: None,
            args: None,
            existing_contracts: None,
            input_assets: None,
            dust_amount: None,
        }
    }
}

