/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum TxStatus {
    #[serde(rename="Confirmed")]
    Confirmed(Box<models::Confirmed>),
    #[serde(rename="MemPooled")]
    MemPooled,
    #[serde(rename="TxNotFound")]
    TxNotFound,
}

impl Default for TxStatus {
    fn default() -> Self {
        Self::TxNotFound
    }
}


