/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", content = "value")]
pub enum Val {
    #[serde(rename="Address")]
    ValAddress(String),
    #[serde(rename="Array")]
    ValArray(Box<Vec<Val>>),
    #[serde(rename="Bool")]
    ValBool(bool),
    #[serde(rename="ByteVec")]
    ValByteVec(String),
    #[serde(rename="I256")]
    ValI256(String),
    #[serde(rename="U256")]
    ValU256(String),
}

impl Default for Val {
    fn default() -> Self {
        Self::ValAddress(Default::default())
    }
}


