/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifySignature {
    #[serde(rename = "data")]
    pub data: String,
    #[serde(rename = "signature")]
    pub signature: String,
    #[serde(rename = "publicKey")]
    pub public_key: String,
}

impl VerifySignature {
    pub fn new(data: String, signature: String, public_key: String) -> VerifySignature {
        VerifySignature {
            data,
            signature,
            public_key,
        }
    }
}

