/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WalletStatus {
    #[serde(rename = "walletName")]
    pub wallet_name: String,
    #[serde(rename = "locked")]
    pub locked: bool,
}

impl WalletStatus {
    pub fn new(wallet_name: String, locked: bool) -> WalletStatus {
        WalletStatus {
            wallet_name,
            locked,
        }
    }
}

