/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WalletRestore {
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "mnemonic")]
    pub mnemonic: String,
    #[serde(rename = "walletName")]
    pub wallet_name: String,
    #[serde(rename = "isMiner", skip_serializing_if = "Option::is_none")]
    pub is_miner: Option<bool>,
    #[serde(rename = "mnemonicPassphrase", skip_serializing_if = "Option::is_none")]
    pub mnemonic_passphrase: Option<String>,
}

impl WalletRestore {
    pub fn new(password: String, mnemonic: String, wallet_name: String) -> WalletRestore {
        WalletRestore {
            password,
            mnemonic,
            wallet_name,
            is_miner: None,
            mnemonic_passphrase: None,
        }
    }
}

