/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddressInfo {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "publicKey")]
    pub public_key: String,
    #[serde(rename = "group")]
    pub group: i32,
    #[serde(rename = "path")]
    pub path: String,
}

impl AddressInfo {
    pub fn new(address: String, public_key: String, group: i32, path: String) -> AddressInfo {
        AddressInfo {
            address,
            public_key,
            group,
            path,
        }
    }
}

