/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Addresses {
    #[serde(rename = "activeAddress")]
    pub active_address: String,
    #[serde(rename = "addresses")]
    pub addresses: Vec<models::AddressInfo>,
}

impl Addresses {
    pub fn new(active_address: String, addresses: Vec<models::AddressInfo>) -> Addresses {
        Addresses {
            active_address,
            addresses,
        }
    }
}

