/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetState {
    #[serde(rename = "attoAlphAmount")]
    pub atto_alph_amount: String,
    #[serde(rename = "tokens", skip_serializing_if = "Option::is_none")]
    pub tokens: Option<Vec<models::Token>>,
}

impl AssetState {
    pub fn new(atto_alph_amount: String) -> AssetState {
        AssetState {
            atto_alph_amount,
            tokens: None,
        }
    }
}

