/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetInput {
    #[serde(rename = "outputRef")]
    pub output_ref: Box<models::OutputRef>,
    #[serde(rename = "unlockScript")]
    pub unlock_script: String,
}

impl AssetInput {
    pub fn new(output_ref: models::OutputRef, unlock_script: String) -> AssetInput {
        AssetInput {
            output_ref: Box::new(output_ref),
            unlock_script,
        }
    }
}

