/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockHeaderEntry {
    #[serde(rename = "hash")]
    pub hash: String,
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    #[serde(rename = "chainFrom")]
    pub chain_from: i32,
    #[serde(rename = "chainTo")]
    pub chain_to: i32,
    #[serde(rename = "height")]
    pub height: i32,
    #[serde(rename = "deps")]
    pub deps: Vec<String>,
}

impl BlockHeaderEntry {
    pub fn new(hash: String, timestamp: i64, chain_from: i32, chain_to: i32, height: i32, deps: Vec<String>) -> BlockHeaderEntry {
        BlockHeaderEntry {
            hash,
            timestamp,
            chain_from,
            chain_to,
            height,
            deps,
        }
    }
}

