/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockAndEvents {
    #[serde(rename = "block")]
    pub block: Box<models::BlockEntry>,
    #[serde(rename = "events")]
    pub events: Vec<models::ContractEventByBlockHash>,
}

impl BlockAndEvents {
    pub fn new(block: models::BlockEntry, events: Vec<models::ContractEventByBlockHash>) -> BlockAndEvents {
        BlockAndEvents {
            block: Box::new(block),
            events,
        }
    }
}

