/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BrokerInfoAddress {
    #[serde(rename = "addr")]
    pub addr: String,
    #[serde(rename = "port")]
    pub port: i32,
}

impl BrokerInfoAddress {
    pub fn new(addr: String, port: i32) -> BrokerInfoAddress {
        BrokerInfoAddress {
            addr,
            port,
        }
    }
}

