/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildChainedDeployContractTx {
    #[serde(rename = "value")]
    pub value: Box<models::BuildDeployContractTx>,
}

impl BuildChainedDeployContractTx {
    pub fn new(value: models::BuildDeployContractTx) -> BuildChainedDeployContractTx {
        BuildChainedDeployContractTx { value: Box::new(value) }
    }
}

