/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildInfo {
    #[serde(rename = "releaseVersion")]
    pub release_version: String,
    #[serde(rename = "commit")]
    pub commit: String,
}

impl BuildInfo {
    pub fn new(release_version: String, commit: String) -> BuildInfo {
        BuildInfo {
            release_version,
            commit,
        }
    }
}

