/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", content = "value")]
pub enum BuildChainedTx {
    #[serde(rename="DeployContract")]
    BuildChainedDeployContractTx(Box<models::BuildDeployContractTx>),
    #[serde(rename="ExecuteScript")]
    BuildChainedExecuteScriptTx(Box<models::BuildExecuteScriptTx>),
    #[serde(rename="Transfer")]
    BuildChainedTransferTx(Box<models::BuildTransferTx>),
}

impl Default for BuildChainedTx {
    fn default() -> Self {
        Self::BuildChainedDeployContractTx(Default::default())
    }
}


