/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum BuildChainedTx {
    #[serde(rename="BuildChainedDeployContractTx")]
    BuildChainedDeployContractTx(Box<models::BuildChainedDeployContractTx>),
    #[serde(rename="BuildChainedExecuteScriptTx")]
    BuildChainedExecuteScriptTx(Box<models::BuildChainedExecuteScriptTx>),
    #[serde(rename="BuildChainedTransferTx")]
    BuildChainedTransferTx(Box<models::BuildChainedTransferTx>),
}

impl Default for BuildChainedTx {
    fn default() -> Self {
        Self::BuildChainedDeployContractTx(Default::default())
    }
}


