/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildDeployContractTx {
    #[serde(rename = "fromPublicKey")]
    pub from_public_key: String,
    #[serde(rename = "fromPublicKeyType", skip_serializing_if = "Option::is_none")]
    pub from_public_key_type: Option<String>,
    #[serde(rename = "bytecode")]
    pub bytecode: String,
    #[serde(rename = "initialAttoAlphAmount", skip_serializing_if = "Option::is_none")]
    pub initial_atto_alph_amount: Option<String>,
    #[serde(rename = "initialTokenAmounts", skip_serializing_if = "Option::is_none")]
    pub initial_token_amounts: Option<Vec<models::Token>>,
    #[serde(rename = "issueTokenAmount", skip_serializing_if = "Option::is_none")]
    pub issue_token_amount: Option<String>,
    #[serde(rename = "issueTokenTo", skip_serializing_if = "Option::is_none")]
    pub issue_token_to: Option<String>,
    #[serde(rename = "gasAmount", skip_serializing_if = "Option::is_none")]
    pub gas_amount: Option<i32>,
    #[serde(rename = "gasPrice", skip_serializing_if = "Option::is_none")]
    pub gas_price: Option<String>,
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<i32>,
    #[serde(rename = "targetBlockHash", skip_serializing_if = "Option::is_none")]
    pub target_block_hash: Option<String>,
}

impl BuildDeployContractTx {
    pub fn new(from_public_key: String, bytecode: String) -> BuildDeployContractTx {
        BuildDeployContractTx {
            from_public_key,
            from_public_key_type: None,
            bytecode,
            initial_atto_alph_amount: None,
            initial_token_amounts: None,
            issue_token_amount: None,
            issue_token_to: None,
            gas_amount: None,
            gas_price: None,
            group: None,
            target_block_hash: None,
        }
    }
}

