/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildSweepAddressTransactions {
    #[serde(rename = "fromPublicKey")]
    pub from_public_key: String,
    #[serde(rename = "fromPublicKeyType", skip_serializing_if = "Option::is_none")]
    pub from_public_key_type: Option<String>,
    #[serde(rename = "toAddress")]
    pub to_address: String,
    #[serde(rename = "maxAttoAlphPerUTXO", skip_serializing_if = "Option::is_none")]
    pub max_atto_alph_per_utxo: Option<String>,
    #[serde(rename = "lockTime", skip_serializing_if = "Option::is_none")]
    pub lock_time: Option<i64>,
    #[serde(rename = "gasAmount", skip_serializing_if = "Option::is_none")]
    pub gas_amount: Option<i32>,
    #[serde(rename = "gasPrice", skip_serializing_if = "Option::is_none")]
    pub gas_price: Option<String>,
    #[serde(rename = "targetBlockHash", skip_serializing_if = "Option::is_none")]
    pub target_block_hash: Option<String>,
    #[serde(rename = "utxosLimit", skip_serializing_if = "Option::is_none")]
    pub utxos_limit: Option<i32>,
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<i32>,
}

impl BuildSweepAddressTransactions {
    pub fn new(from_public_key: String, to_address: String) -> BuildSweepAddressTransactions {
        BuildSweepAddressTransactions {
            from_public_key,
            from_public_key_type: None,
            to_address,
            max_atto_alph_per_utxo: None,
            lock_time: None,
            gas_amount: None,
            gas_price: None,
            target_block_hash: None,
            utxos_limit: None,
            group: None,
        }
    }
}

