/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CallTxScript {
    #[serde(rename = "group")]
    pub group: i32,
    #[serde(rename = "bytecode")]
    pub bytecode: String,
    #[serde(rename = "callerAddress", skip_serializing_if = "Option::is_none")]
    pub caller_address: Option<String>,
    #[serde(rename = "worldStateBlockHash", skip_serializing_if = "Option::is_none")]
    pub world_state_block_hash: Option<String>,
    #[serde(rename = "txId", skip_serializing_if = "Option::is_none")]
    pub tx_id: Option<String>,
    #[serde(rename = "inputAssets", skip_serializing_if = "Option::is_none")]
    pub input_assets: Option<Vec<models::TestInputAsset>>,
    #[serde(rename = "interestedContracts", skip_serializing_if = "Option::is_none")]
    pub interested_contracts: Option<Vec<String>>,
}

impl CallTxScript {
    pub fn new(group: i32, bytecode: String) -> CallTxScript {
        CallTxScript {
            group,
            bytecode,
            caller_address: None,
            world_state_block_hash: None,
            tx_id: None,
            input_assets: None,
            interested_contracts: None,
        }
    }
}

