/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CallContractFailed {
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl CallContractFailed {
    pub fn new(error: String, r#type: String) -> CallContractFailed {
        CallContractFailed {
            error,
            r#type,
        }
    }
}

