/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeActiveAddress {
    #[serde(rename = "address")]
    pub address: String,
}

impl ChangeActiveAddress {
    pub fn new(address: String) -> ChangeActiveAddress {
        ChangeActiveAddress {
            address,
        }
    }
}

