/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompilerOptions {
    #[serde(rename = "ignoreUnusedConstantsWarnings", skip_serializing_if = "Option::is_none")]
    pub ignore_unused_constants_warnings: Option<bool>,
    #[serde(rename = "ignoreUnusedVariablesWarnings", skip_serializing_if = "Option::is_none")]
    pub ignore_unused_variables_warnings: Option<bool>,
    #[serde(rename = "ignoreUnusedFieldsWarnings", skip_serializing_if = "Option::is_none")]
    pub ignore_unused_fields_warnings: Option<bool>,
    #[serde(rename = "ignoreUnusedPrivateFunctionsWarnings", skip_serializing_if = "Option::is_none")]
    pub ignore_unused_private_functions_warnings: Option<bool>,
    #[serde(rename = "ignoreUpdateFieldsCheckWarnings", skip_serializing_if = "Option::is_none")]
    pub ignore_update_fields_check_warnings: Option<bool>,
    #[serde(rename = "ignoreCheckExternalCallerWarnings", skip_serializing_if = "Option::is_none")]
    pub ignore_check_external_caller_warnings: Option<bool>,
    #[serde(rename = "ignoreUnusedFunctionReturnWarnings", skip_serializing_if = "Option::is_none")]
    pub ignore_unused_function_return_warnings: Option<bool>,
    #[serde(rename = "skipAbstractContractCheck", skip_serializing_if = "Option::is_none")]
    pub skip_abstract_contract_check: Option<bool>,
    #[serde(rename = "skipTests", skip_serializing_if = "Option::is_none")]
    pub skip_tests: Option<bool>,
}

impl CompilerOptions {
    pub fn new() -> CompilerOptions {
        CompilerOptions {
            ignore_unused_constants_warnings: None,
            ignore_unused_variables_warnings: None,
            ignore_unused_fields_warnings: None,
            ignore_unused_private_functions_warnings: None,
            ignore_update_fields_check_warnings: None,
            ignore_check_external_caller_warnings: None,
            ignore_unused_function_return_warnings: None,
            skip_abstract_contract_check: None,
            skip_tests: None,
        }
    }
}

