/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractEventByTxId {
    #[serde(rename = "blockHash")]
    pub block_hash: String,
    #[serde(rename = "contractAddress")]
    pub contract_address: String,
    #[serde(rename = "eventIndex")]
    pub event_index: i32,
    #[serde(rename = "fields")]
    pub fields: Vec<models::Val>,
}

impl ContractEventByTxId {
    pub fn new(block_hash: String, contract_address: String, event_index: i32, fields: Vec<models::Val>) -> ContractEventByTxId {
        ContractEventByTxId {
            block_hash,
            contract_address,
            event_index,
            fields,
        }
    }
}

