/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractEvents {
    #[serde(rename = "events")]
    pub events: Vec<models::ContractEvent>,
    #[serde(rename = "nextStart")]
    pub next_start: i32,
}

impl ContractEvents {
    pub fn new(events: Vec<models::ContractEvent>, next_start: i32) -> ContractEvents {
        ContractEvents {
            events,
            next_start,
        }
    }
}

