/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractEventsByBlockHash {
    #[serde(rename = "events")]
    pub events: Vec<models::ContractEventByBlockHash>,
}

impl ContractEventsByBlockHash {
    pub fn new(events: Vec<models::ContractEventByBlockHash>) -> ContractEventsByBlockHash {
        ContractEventsByBlockHash {
            events,
        }
    }
}

