/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Contract {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "compilerOptions", skip_serializing_if = "Option::is_none")]
    pub compiler_options: Option<Box<models::CompilerOptions>>,
}

impl Contract {
    pub fn new(code: String) -> Contract {
        Contract {
            code,
            compiler_options: None,
        }
    }
}

