/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum DiscoveryAction {
    #[serde(rename="Reachable")]
    Reachable(Box<models::Reachable>),
    #[serde(rename="Unreachable")]
    Unreachable(Box<models::Unreachable>),
}

impl Default for DiscoveryAction {
    fn default() -> Self {
        Self::Reachable(Default::default())
    }
}


