/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MempoolTransactions {
    #[serde(rename = "fromGroup")]
    pub from_group: i32,
    #[serde(rename = "toGroup")]
    pub to_group: i32,
    #[serde(rename = "transactions")]
    pub transactions: Vec<models::TransactionTemplate>,
}

impl MempoolTransactions {
    pub fn new(from_group: i32, to_group: i32, transactions: Vec<models::TransactionTemplate>) -> MempoolTransactions {
        MempoolTransactions {
            from_group,
            to_group,
            transactions,
        }
    }
}

