/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MinerAddresses {
    #[serde(rename = "addresses")]
    pub addresses: Vec<String>,
}

impl MinerAddresses {
    pub fn new(addresses: Vec<String>) -> MinerAddresses {
        MinerAddresses {
            addresses,
        }
    }
}

