/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum MisbehaviorAction {
    #[serde(rename="Ban")]
    Ban(Box<models::Ban>),
    #[serde(rename="Unban")]
    Unban(Box<models::Unban>),
}

impl Default for MisbehaviorAction {
    fn default() -> Self {
        Self::Ban(Default::default())
    }
}


