/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MultipleCallContract {
    #[serde(rename = "calls")]
    pub calls: Vec<models::CallContract>,
}

impl MultipleCallContract {
    pub fn new(calls: Vec<models::CallContract>) -> MultipleCallContract {
        MultipleCallContract {
            calls,
        }
    }
}

