/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodeInfo {
    #[serde(rename = "buildInfo")]
    pub build_info: Box<models::BuildInfo>,
    #[serde(rename = "upnp")]
    pub upnp: bool,
    #[serde(rename = "externalAddress", skip_serializing_if = "Option::is_none")]
    pub external_address: Option<Box<models::BrokerInfoAddress>>,
}

impl NodeInfo {
    pub fn new(build_info: models::BuildInfo, upnp: bool) -> NodeInfo {
        NodeInfo {
            build_info: Box::new(build_info),
            upnp,
            external_address: None,
        }
    }
}

