/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutputRef {
    #[serde(rename = "hint")]
    pub hint: i32,
    #[serde(rename = "key")]
    pub key: String,
}

impl OutputRef {
    pub fn new(hint: i32, key: String) -> OutputRef {
        OutputRef {
            hint,
            key,
        }
    }
}

