/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Output {
    #[serde(rename="AssetOutput")]
    AssetOutput(Box<models::AssetOutput>),
    #[serde(rename="ContractOutput")]
    ContractOutput(Box<models::ContractOutput>),
}

impl Default for Output {
    fn default() -> Self {
        Self::AssetOutput(Default::default())
    }
}


