/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Penalty {
    #[serde(rename = "value")]
    pub value: i32,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl Penalty {
    pub fn new(value: i32, r#type: String) -> Penalty {
        Penalty {
            value,
            r#type,
        }
    }
}

