/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RichBlockEntry {
    #[serde(rename = "hash")]
    pub hash: String,
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    #[serde(rename = "chainFrom")]
    pub chain_from: i32,
    #[serde(rename = "chainTo")]
    pub chain_to: i32,
    #[serde(rename = "height")]
    pub height: i32,
    #[serde(rename = "deps")]
    pub deps: Vec<String>,
    #[serde(rename = "transactions")]
    pub transactions: Vec<models::RichTransaction>,
    #[serde(rename = "nonce")]
    pub nonce: String,
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "depStateHash")]
    pub dep_state_hash: String,
    #[serde(rename = "txsHash")]
    pub txs_hash: String,
    #[serde(rename = "target")]
    pub target: String,
    #[serde(rename = "ghostUncles")]
    pub ghost_uncles: Vec<models::GhostUncleBlockEntry>,
}

impl RichBlockEntry {
    pub fn new(hash: String, timestamp: i64, chain_from: i32, chain_to: i32, height: i32, deps: Vec<String>, transactions: Vec<models::RichTransaction>, nonce: String, version: i32, dep_state_hash: String, txs_hash: String, target: String, ghost_uncles: Vec<models::GhostUncleBlockEntry>) -> RichBlockEntry {
        RichBlockEntry {
            hash,
            timestamp,
            chain_from,
            chain_to,
            height,
            deps,
            transactions,
            nonce,
            version,
            dep_state_hash,
            txs_hash,
            target,
            ghost_uncles,
        }
    }
}

