/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubContracts {
    #[serde(rename = "subContracts")]
    pub sub_contracts: Vec<String>,
    #[serde(rename = "nextStart")]
    pub next_start: i32,
}

impl SubContracts {
    pub fn new(sub_contracts: Vec<String>, next_start: i32) -> SubContracts {
        SubContracts {
            sub_contracts,
            next_start,
        }
    }
}

