/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitTransaction {
    #[serde(rename = "unsignedTx")]
    pub unsigned_tx: String,
    #[serde(rename = "signature")]
    pub signature: String,
}

impl SubmitTransaction {
    pub fn new(unsigned_tx: String, signature: String) -> SubmitTransaction {
        SubmitTransaction {
            unsigned_tx,
            signature,
        }
    }
}

