/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SweepAddressTransaction {
    #[serde(rename = "txId")]
    pub tx_id: String,
    #[serde(rename = "unsignedTx")]
    pub unsigned_tx: String,
    #[serde(rename = "gasAmount")]
    pub gas_amount: i32,
    #[serde(rename = "gasPrice")]
    pub gas_price: String,
}

impl SweepAddressTransaction {
    pub fn new(tx_id: String, unsigned_tx: String, gas_amount: i32, gas_price: String) -> SweepAddressTransaction {
        SweepAddressTransaction {
            tx_id,
            unsigned_tx,
            gas_amount,
            gas_price,
        }
    }
}

