/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionTemplate {
    #[serde(rename = "unsigned")]
    pub unsigned: Box<models::UnsignedTx>,
    #[serde(rename = "inputSignatures")]
    pub input_signatures: Vec<String>,
    #[serde(rename = "scriptSignatures")]
    pub script_signatures: Vec<String>,
    #[serde(rename = "seenAt")]
    pub seen_at: i64,
}

impl TransactionTemplate {
    pub fn new(unsigned: models::UnsignedTx, input_signatures: Vec<String>, script_signatures: Vec<String>, seen_at: i64) -> TransactionTemplate {
        TransactionTemplate {
            unsigned: Box::new(unsigned),
            input_signatures,
            script_signatures,
            seen_at,
        }
    }
}

