/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Val {
    #[serde(rename="ValAddress")]
    ValAddress(Box<models::ValAddress>),
    #[serde(rename="ValArray")]
    ValArray(Box<models::ValArray>),
    #[serde(rename="ValBool")]
    ValBool(Box<models::ValBool>),
    #[serde(rename="ValByteVec")]
    ValByteVec(Box<models::ValByteVec>),
    #[serde(rename="ValI256")]
    ValI256(Box<models::ValI256>),
    #[serde(rename="ValU256")]
    ValU256(Box<models::ValU256>),
}

impl Default for Val {
    fn default() -> Self {
        Self::ValAddress(Default::default())
    }
}


