/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValArray {
    #[serde(rename = "value")]
    pub value: Vec<models::Val>,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl ValArray {
    pub fn new(value: Vec<models::Val>, r#type: String) -> ValArray {
        ValArray {
            value,
            r#type,
        }
    }
}

