/*
 * Alephium API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.15.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WalletUnlock {
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "mnemonicPassphrase", skip_serializing_if = "Option::is_none")]
    pub mnemonic_passphrase: Option<String>,
}

impl WalletUnlock {
    pub fn new(password: String) -> WalletUnlock {
        WalletUnlock {
            password,
            mnemonic_passphrase: None,
        }
    }
}

